### ISSUE TITLE
Please update openhub

### ISSUE THREAD

**Issue by bluefox16** [volca02/openDarkEngine#24]
In particular:

https://www.openhub.net/p/opde/enlistments

The project homepage: (You can link it to github)

https://www.openhub.net/p/opde/links

Also please add the game_engine_recreation tag.

You might want to consider allowing any registered user to edit the project (that would have saved you the trouble).

Cool project btw

**Comment by volca02** [comment]
Thanks for the heads-up, didn't even know this was still up. I updated what I saw was wrong.

**Comment by bluefox16** [comment]
White we are at it, could you also add the game_engine_recreation tag?

**Comment by bluefox16** [comment]
Thanks!
